### ISSUE TITLE
Issues Step 2 - task 15

### ISSUE THREAD

**Issue by AnneNorling** [chriskarlsson/1DV433#2]
Uppgift 15:
Programmet ska presentera ..."på vilka fortsatta födelsedagar" som nya askar måste köpas.
Testfallet anger att ...
#1: "Nästa ask köper han vid 7 års ålder" - ditt program svarar att 1 ask köps vid 1 års ålder.
#2: "När han fyller 97 år måste han köpa fem askar" - ditt program svarar 4.
Korrigera dessa två buggar för korrekt funktion innan godkännande.

**Comment by chriskarlsson** [comment]
Fixade kommentarerna.

**Comment by AnneNorling** [comment]
OK och godkänt!
